### ISSUE TITLE
Adjust file naming pattern

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/lake-temperature-missouri-models#17]
Based on how [the other feathers are named for NLDAS](https://github.com/USGS-R/lake-temperature-out/blob/main/1_fetch.yml#L216-L217) (`[model]_[site]_[driver].feather`), I renamed these files before uploading to SB. 

`GLM_calibrated_[site_id]_NLDAS.feather`

**Comment by padilla410** [comment]
I'll take care of this issue in a tiny PR later this week
